### ISSUE TITLE
Second arriving VoLTE call crashes modem

### ISSUE THREAD

**Issue by Alaraajavamma** [Biktorgj/pinephone_modem_sdk#104]
Hello! 
There is this known issue in Gnome-Calls:
https://gitlab.gnome.org/GNOME/calls/-/issues/428
I have been looking for a decent workaround for a sometime and last time I tested things I noticed this:
With Biktorgjs firmware all connections crash when you are speaking ongoing VoLTE call and someone else calls you at same time. "The second call" is also problematic with stock firmware but it doesn't completely break the connection - only the call is disconnected or both calls or the sound is disconnected (depends somehow from network xD) 
When you are in 2G or 3G it only cuts callaudio (as descriped in Gnome-Calls issue)

I attached the log files - they are generated with kkeijzer's script right after "the second killer call starts".
Tried to look those but did not understand much. 
This whole thing might be also related to something else than this firmware but I am reporting it here because this problem does not occur in stock firmware. 

Might be related but most likely not: 
It is also strange that "call forwarding when busy" is not working on VoLTE calls -> my guess is that Finnish carriers (tried them all xD) does not understand/see when Pinephone is actively speaking VoLTE call. Call forwarding is working with 2G and 3G. But this is same situation with stock firmware. 

[eg25-manager.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8808892/eg25-manager.log)
[modemmanager.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8808893/modemmanager.log)
[networkmanager.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8808894/networkmanager.log)
[openqti.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8808895/openqti.log)
[dmesg-modem.txt](https://github.com/Biktorgj/pinephone_modem_sdk/files/8808890/dmesg-modem.txt)
[dmesg-pinephone.txt](https://github.com/Biktorgj/pinephone_modem_sdk/files/8808891/dmesg-pinephone.txt)

**Comment by Biktorgj** [comment]
Hi!
You found a bug in OpenQTI! I can tell from a race condition that ends up in a null pointer dereference showing up in the modem kernel log. That's because openqti died but one of its threads wasn't really dead yet when it respawned, ending up in two threads trying to write to the same device at the same time

You have persistent storage enabled, so the openqti.log you attached is empty (only some remnants of the config file parsing show up).

Please run `adb pull /persist/openqti.log.X` where X is the number of times you rebooted since you collected the log.

You can also get all of them by running  `adb pull /persist/` and then go hunting for the correct file inside the logs. When openqti starts, it always prints a message saying "Welcome to OpenQTI Version X.X.X". In the log file where you had the crash, you should see that message twice, once at the head of the logfile, and then another one through the end

Can you post it here? (Beware of phone numbers/sms written in the log)

**Comment by Alaraajavamma** [comment]
Here you go. 
For dummy user like me lines 126-130 looks strange:
Line 126: W mask_phone_number: 358XXXXXXXXX358XXXXX************************************************* --> ************************************************* (52)
First "358" starting number is the "second killer call" but without break there is _part_ of the first number - not fully but is absolutely part. Same continues on next lines - it looks like it combines those numbers :D

Edit. @Biktorgj sorry that I ping you - hope it doesn't bother you :). I'm just not sure did you notice this post already. I hope the file is correct now? for me it looks like correct :D.

[openqti.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8811398/openqti.log)

**Comment by Biktorgj** [comment]
Sorry @Alaraajavamma, been busy fighting other stuff....

Can you try this build for me? I had some ugly conversions in the source string for mask_phone_number that I hadn't notice. Let's see if this works, otherwise I might just nuke the function out of orbit and stop logging that altoghether

[
[package.tar.gz](https://github.com/Biktorgj/pinephone_modem_sdk/files/8839372/package.tar.gz)
](url)

**Comment by Alaraajavamma** [comment]
No problem I understand how this works :). You will help if you have time (and you want to do) -no matter how long it takes I’m grateful if you help.

It does something differently but the main problem is still the same. Second call "stucks" the modem - you can't kill the first call so you have to wait as long as another part cuts it off or you shutdown the modem. If you wait long enough the modem will crash itself.

Edit. And the package.tar.gz did not have all usual files so I borrowed the missing files from 0.65. Was that in purpose :D?

[dmesg-modem.txt](https://github.com/Biktorgj/pinephone_modem_sdk/files/8840253/dmesg-modem.txt)
[dmesg-pinephone.txt](https://github.com/Biktorgj/pinephone_modem_sdk/files/8840254/dmesg-pinephone.txt)
[eg25-manager.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8840256/eg25-manager.log)
[modemmanager.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8840257/modemmanager.log)
[networkmanager.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8840258/networkmanager.log)
[openqti.log](https://github.com/Biktorgj/pinephone_modem_sdk/files/8840259/openqti.log)

**Comment by Biktorgj** [comment]
Fixes were merged for 0.6.6 and refined in 0.6.7, so this should be working fine now :)
Closing the issue, feel free to reopen if you find something else!
