### ISSUE TITLE
off-topic: buy a coffee without paypal

### ISSUE THREAD

**Issue by chri2** [Biktorgj/pinephone_modem_sdk#105]
[@mobian](https://fosstodon.org/@mobian) asked on [mastodon](https://fosstodon.org/@mobian/108262769072160603) to support you and I'd have loved to buy you a coffee or two. But the site mentioned would require me to open a paypal account which I terminated a long time ago and wouldn't open again.

If you care for some more coffee I'd love to invite you if you offer a simple privacy friendly way to pay for it (if we do not meet in person somewhere somewhen ;-) ).

**Comment by ghost** [comment]
sounds like sats on lightning...

**Comment by Biktorgj** [comment]
I'm not going to lie, I didn't pay much attention to it when I signed up on ko-fi, but it seemed like the most user-friendly way of doing it without having to pay fees on each transaction.

As far as I've seen, most people either use Ko-fi, Paypal directly, stripe, or Github Sponsors, but none of the choices seem to be really privacy friendly :)

Ideas welcome :) (please no crypto ;))

**Comment by ghost** [comment]
Liberapay? https://liberapay.com/

Ive never used it just see it used on open projects sometimes

**Comment by Biktorgj** [comment]
So I took a look at Liberapay.
Basically the same as Ko-fi but without trying to get you to pay "Premium" all the time :)
Both support Paypal and Stripe, so I enabled both on both platforms.
Not that Stripe is anonymous by any means but... well I guess, there aren't so many stories on the Internet on how stripe locked the funds of someone because they moved 30km away of the usual location and got their money.

Anyway, https://liberapay.com/biktorgj/donate or https://ko-fi.com/biktorgj, everyone is free to do whatever they want ;)

PS: One thing I don't like from Liberapay is that it tries to get you to do a recurring donation by default, and you can only "manually review" when it's time to renew by week/month/year, so if you want to do a one-off you need to select a weekly with manual review just to ignore it later or something...
