### ISSUE TITLE
Echo cancellation

### ISSUE THREAD

**Issue by bunglesss** [Biktorgj/pinephone_modem_sdk#147]
Hi,

Did I read somewhere the closed firmware had echo cancellation, and the new open source version hasn't got it? Is this correct?

**Comment by Biktorgj** [comment]
Yes, the closed firmware has some voice calibration profiles that are loaded on boot, that tune up audio, and seem to do some basic echo cancellation and automatic gain control in calls, and that's not available in the opensource firmware (all in that is closed source and besides the problems derived of actually making that work there's the licensing issue where we might not be legally able to redistribute those calibration files)

**Comment by bunglesss** [comment]
Interesting, thanks for sharing that I only ask because so far I've found the PPP unusable for making phone calls, everyone who calls me can hear themselves echo back.

I did try with the stock firmware and found it unusable there too.

I'm not sure how much of this is echo cancellation, and how much these mic boost/volume settings I've seen posted about, and how much about the hardware ... not sure if I saw something saying the mic might physically be too close to the speaker or something.

**Comment by CodePhase** [comment]
@bunglesss I don't think ti's the speaker being too close to the mic on the PPP.  I have been experimenting with this issue for quite some time (on Mobian) and found the "other side echo" persists even when the PPP is face down on my couch, which should at least reduce the echo if that was the cause, but it doesn't.

I found that if I mute the microphone on the PPP that the echo disappears.  I don't know if this is an issue with the modem firmware, the ADSP, or ALSA (UCM profiles).  My guess is that the issue is something either in the audio codec used in the kernel or the UCM profile or a combination of both.  Unfortunately I still haven't gotten to the bottom of it and it's the last major complaint I get when using this phone.

I actually created an issue with Mobian about this [here](https://salsa.debian.org/Mobian-team/devices/pinephonepro-support/-/issues/9), which was imported from the previous Mobian Gitlab instance to the current one.

**Comment by bunglesss** [comment]
Well, can't fault you as you seen to have done some digging here, but signs point then to maybe pinephone sound card driver then, but not your firmware. Can't see it being pulse audio/pipewire as issue seems to be there on both, so must be lower down the stack than that.

I'll close this anyway, and keep an eye on that other bug you linked.

Thanks for all your help.

**Comment by baptx** [comment]
With the PinePhone on Mobian 13, using the original firmware 30.006.30.006 from https://github.com/Biktorgj/quectel_eg25_recovery fixed the echo. Decreasing the microphone volume and loudspeaker volume in Phosh sound settings can also help (on the previous version of Mobian, the solution was a bit different: https://forum.pine64.org/showthread.php?tid=16930&pid=122436#pid122436).
On the custom firmware, I was not able to fix the echo so I think this issue can be reopened.

**Comment by baptx** [comment]
Pipewire also has an echo cancel module but it did not fix the issue on the custom firmware:
https://docs.pipewire.org/page_module_echo_cancel.html

In the file `/usr/share/alsa/ucm2/Allwinner/A64/PinePhone/PinePhone.conf` I also tried changing the values of "AIF2 DAC Playback Volume" and "AIF2 ADC Capture Volume" from 160 (there was no character "%" at the end) to 80% like mentioned on https://github.com/the-modem-distro/pinephone_modem_sdk/blob/scarthgap/docs/SETTINGS.md#pinephone.
After rebooting, it did not fix the issue.
