### ISSUE TITLE
EG25GGBR07A08M2G_01.001.01.001

### ISSUE THREAD

**Issue by RUzOfuz5m** [Biktorgj/pinephone_modem_sdk#235]
I have `EG25GGBR07A08M2G_01.001.01.001` on my phone. If someone can provide the instructions to back it up I'll make it public if it's of interest 

```
root@ubuntu-phablet:~# echo 'AT+QGMR' | sudo atinout - /dev/ttyUSB3 -
+QGPSURC: "xtradataexpire",0,"2024/04/17,13:00:00"
AT+QGMR
EG25GGBR07A08M2G_01.001.01.001
OK
root@ubuntu-phablet:~# 
```

**Comment by UltraBlackLinux** [comment]
I don't think you can back these up. what quectel want you to do is shoot them a mail with your current firmware version and they'll send you the newest one.
Just been through this data collection hell. It's a pain in the arse.

**Comment by RUzOfuz5m** [comment]
That sounds lovely.  If that's the case then what I have isn't useful to the community so I'll close this issue and upgrade to a different version. I'll leave this open for a while longer to see if anyone else has anything to say.

**Comment by Zapeth** [comment]
@RUzOfuz5m In case you haven't installed a different firmware yet, it is indeed possible to dump the pre-installed firmware for backup purposes -> https://github.com/Biktorgj/quectel_eg25_recovery/issues/6#issuecomment-876920200

As mentioned it should also be possible to restore the firmware from the dumped files, though I haven't had the need to do so since the newer firmware seems to work fine.
